config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :prestation_orders, :except => [:edit, :destroy, :update, :index, :show]
  get '/prestation_orders/new/step:step_number' => 'prestation_orders#new'
  get 'welcome/index', as: 'show_welcome'
  root 'welcome#index'

  get '/galerie' => 'galeries#index', as: 'show_galery'
  get '/about' => 'welcome#about'
  get '/prestations' => 'prestations#index'
  get "/show_categories/:id" => 'galeries#show_categories', as: 'show_categories'
  get "/show_categories_all" => 'galeries#show_categories_all', as: 'show_categories_all'
  get "/success" => 'prestation_orders#success', as: 'show_prestation_success'
 # resources :galeries, only: [:index, :new, :create]

end

app/models/galery.rb
class Galery < ApplicationRecord
  belongs_to :photosvideo
  validate :validate_url
	def media
    "https://www.youtube.com/embed/#{self.uid}"
	end
	def media2
		"https://img.youtube.com/vi/#{self.uid}/hqdefault.jpg"
	end
	def media3
		self.uid
	end
	#Model repris depuis https://www.sitepoint.com/youtube-rails/. Une modification du regex à du être adapté pour que cela fonctionne.
	#Ajout d'un attribut virtuel car c'est inutile de sauver le uid et le link comme le sugère le site.
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*\z/i
  def validate_url
    uid = self.uid.match(YT_LINK_FORMAT)
    self.uid = uid[2] if uid && uid[2]
    if self.uid.to_s.length != 11
      self.errors.add(:uid, 'is invalid.')
      false
    end
  end
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
  def index
  @categories = Category.order('name ASC')
  @category = params[:category]
  @type     = params[:type]


  # XXX Ceci est en doublon plus bas, il n'y aurait pas plus simple?
  @pictures = media(Picture).page(params[:picture_page]).per(6) if @type == "pictures"
  @videos   = media(Video).page(params[:video_page]).per(6) if @type == "videos"

  @category = "All" if @category.blank?
  @type = "both" if @type.blank?
  if  @type == "both"
    @pictures = media(Picture).page(params[:picture_page]).per(6)
    @videos   = media(Video).page(params[:video_page]).per(6)
  end
end


end

private
def media(model)
  if @category == "All" || @category.blank?
    model.order('created_at DESC')
  else
     model.joins(:photosvideo).where("photosvideos.category_id = ?", @category).order('created_at DESC')
  end
end

app/views/galeries/index.html.erb
<div class="container">
	<div class="panel panel-default">
    <div class="panel-heading">
			<div class="row">
				<div class="col-md-18 col-lg-18" id="col-photo-video_id">
					<div class="btn-group btn-group-md">

						<%= link_to show_galery_path(type: "pictures", category: params[:category]), remote: false, id: "btn-pictures", class: "btn btn-default" do %>
   					      <em class="glyphicon glyphicon-picture"></em> Pictures
						<% end %>

						<%= link_to show_galery_path(type: "videos", category: params[:category]), remote: false, id: "btn-videos", class: "btn btn-default" do %>
    					  <em class="glyphicon glyphicon-facetime-video"></em> Vidéos
						<% end %>

						<%= link_to show_galery_path(type: "both", category: params[:category]), :remote => false, :id => "btn-both", :class => "btn btn-default active" do %>
						  <em class="glyphicon glyphicon-duplicate"></em> Les 2
						<% end %>

					</div>
				</div>
				<div class="col-md-60 col-lg-42">
					<ul class="nav nav-pills pull-right">

						<% @categories.each do |c| %>
  						  <li class="" id="btn-filter<%= c.id %>">
   						  <%= link_to show_galery_path(category: c.id, type: params[:type]), remote: false, "data-category-id": c.id, class: "category-id" do %>
    					      <span class="badge pull-right"><%= Photosvideo.joins(:pictures).where(category_id: c.id).count + Photosvideo.joins(:videos).where(category_id: c.id).count  %></span> <%= c.name %>
                              <% end %>
                              </li>
                            <% end %>

						<li class="active " id=btn-filterAll>
   						  <%= link_to show_galery_path(category: 'All', type: params[:type]), remote: false, "data-category-id": 'All', class: "category-id" do %>
    					      <span class="badge pull-right"><%= Photosvideo.joins(:pictures).all.count + Photosvideo.joins(:videos).all.count  %></span> Tous les thèmes
                              <% end %>
						</li>

					</ul>
				</div>
			</div>
		</div>
<!--DEBUT-->
<%= render "shared/modal_picture" %>
<%= render "shared/modal" %>
  <div id="media_filter" class="container">
<%= render partial: 'partials/media_filter', locals: { medias: @videos} %>
<%= render partial: 'partials/media_filter', locals: { medias: @pictures} %>
</div>
<!--FIN-->

</div>
</div>



<%= render partial: 'partials/galery', formats: [:js] %>